Added code to track script error codes during test phase #45

diff --git a/lib/resources/test_spec.yaml b/lib/resources/test_spec.yaml
--- a/lib/resources/test_spec.yaml
+++ b/lib/resources/test_spec.yaml
@@ -23,9 +23,9 @@ phases:
 
       # env
       - env
-      - echo $DEVICEFARM_APP_PATH
       - whoami
       - groups
+      - echo "DEVICEFARM_APP_PATH=$DEVICEFARM_APP_PATH"
 
       # install flutter
       - echo "Install flutter"
@@ -107,6 +107,20 @@ phases:
   # The test phase includes commands that run your test suite execution.
   test:
     commands:
+      - PHASE_FAILED=0
+      - >-
+        track_phase_failure() {
+          local command_failed=$?
+          if [ "$command_failed" != "0" ]; then
+            echo "Most recent command failed with error code: $command_failed"
+            PHASE_FAILED=$command_failed
+          fi
+        }
+
+        set_phase_exit_code() {
+          return $PHASE_FAILED
+        }
+
       # Your test package is downloaded in $DEVICEFARM_TEST_PACKAGE_PATH so we first change directory to that path.
       # We already setup python virtual environment on $DEVICEFARM_TEST_PACKAGE_PATH
       # and installed required libraries. You can run your test under $DEVICEFARM_TEST_PACKAGE_PATH
@@ -126,16 +140,21 @@ phases:
         if [ $DEVICEFARM_DEVICE_PLATFORM_NAME = "Android" ];
         then
           ./script/test_android.sh --run-tests "$TESTS"
+          track_phase_failure
         fi
 
         if [ $DEVICEFARM_DEVICE_PLATFORM_NAME = "iOS" ];
         then
           ./script/test_ios.sh --unpack $DEVICEFARM_APP_PATH
+          track_phase_failure
           ./script/test_ios.sh --dummy-symbols build_to_os.txt
+          track_phase_failure
           ./script/test_ios.sh --run-tests "$MAIN" "$TESTS"
+          track_phase_failure
         fi
 
       - echo done.
+      - set_phase_exit_code
 
   # The post test phase includes are commands that are run after your tests are executed.
   post_test:
